### ISSUE TITLE
Is it now supported umbraco 9 or 10?

### ISSUE THREAD

**Issue by ruder-pratap** [umbracare/UmbraCare.DedicatedMediaFolder.Issues#1]
Hi 
is this package support umbraco 10?

**Comment by piotrbach** [comment]
Hi @ruder-pratap, support for v9/v10 is not ready yet, but will be available soon. Best Regards.

**Comment by piotrbach** [comment]
Hi @ruder-pratap we've just released v9, v10, v11 so all versions are supported now🙂
